### ISSUE TITLE
Dependency error: @webassemblyjs/helper-api-error@1.11.3

### ISSUE THREAD

**Issue by Calvin087** [NEARFoundation/near-contract-parser#3]
Looks like an awesome package. When trying to download

```
npm ERR! code ETARGET
npm ERR! notarget No matching version found for @webassemblyjs/helper-api-error@1.11.3.
npm ERR! notarget In most cases you or one of your dependencies are requesting
npm ERR! notarget a package version that doesn't exist.
```

Is there a way to specify a different version while installing the package?

Thanks

**Comment by encody** [comment]
Looks like [a recent update to the @webassemblyjs/wasm-parser package](https://github.com/xtuc/webassemblyjs/issues/1132#issuecomment-1231088341) specified a nonexistent dependency. I'll get on that. Thanks for reporting!

**Comment by encody** [comment]
Please install [version 0.1.5](https://www.npmjs.com/package/near-contract-parser/v/0.1.5) for the fix.

**Comment by Calvin087** [comment]
holy smokes, that was fast.
Thank you 🫡

![giphy](https://user-images.githubusercontent.com/58273749/193836062-e59f2c6d-05c5-4ecc-be77-1b20190007fa.gif)

**Comment by encody** [comment]
😁😁😁

_imma fast boi_
